version: "3"
services:
  redis:
    image: redis
    ports:
      - "127.0.0.1:6379:6379"
    user: "redis:redis"
  postgres:
    image: postgres
    ports:
      - "127.0.0.1:5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: j4oGODDuAAE4hE6JhlmsYqSKXopvskK5NMGX3UqZFo7C1qt1rGAuaLemUAJoPglD
      POSTGRES_DB: postgres
    user: "postgres:postgres"
