version: "3.2"
services:

  outline:
    image: docker.getoutline.com/outlinewiki/outline:latest
    env_file: ./docker.env
    ports:
      - "3000:3000"
    volumes:
      - storage-data:/var/lib/outline/data
    depends_on:
      - postgres
      - redis

  redis:
    image: redis
    ports:
      - "127.0.0.1:6379:6379"
    user: "redis:redis"
  postgres:
    image: postgres
    ports:
      - "127.0.0.1:5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: j4oGODDuAAE4hE6JhlmsYqSKXopvskK5NMGX3UqZFo7C1qt1rGAuaLemUAJoPglD
      POSTGRES_DB: postgres
    user: "postgres:postgres"

  https-portal:
    image: steveltn/https-portal
    env_file: ./docker.env
    ports:
      - '89:89'
      - '446:446'
    links:
      - outline
    restart: always
    volumes:
      - https-portal-data:/var/lib/https-portal
    healthcheck:
      test: ["CMD", "service","status"]
      interval: 30s
      timeout: 20s
      retries: 3
    environment:
      DOMAINS: 'outline.onlycraft.cloud -> http://outline:3000'
      STAGE: 'production'
      WEBSOCKET: 'true'
      CLIENT_MAX_BODY_SIZE: '0'

volumes:
  https-portal-data:
  storage-data:
  database-data:
